name: Go Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true

      - name: Test
        run: go test -v ./...

      - name: Test Coverage
        run: |
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out 
          
      - name: Run Examples
        run: |
          echo "运行所有示例代码..."
          # 查找并运行所有示例目录中的main.go文件
          for example_dir in examples/*/; do
            if [ -f "${example_dir}main.go" ]; then
              echo "运行示例: ${example_dir}"
              go run ${example_dir}main.go
            fi
          done 